// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: grpc/proto/prices.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_prices_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_prices_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_prices_proto_rawDescGZIP(), []int{0}
}

type Pricing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   string          `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TimeFrom int64           `protobuf:"varint,2,opt,name=timeFrom,proto3" json:"timeFrom,omitempty"`
	TimeTo   int64           `protobuf:"varint,3,opt,name=timeTo,proto3" json:"timeTo,omitempty"`
	Data     []*Pricing_Data `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *Pricing) Reset() {
	*x = Pricing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_prices_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pricing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pricing) ProtoMessage() {}

func (x *Pricing) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_prices_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pricing.ProtoReflect.Descriptor instead.
func (*Pricing) Descriptor() ([]byte, []int) {
	return file_grpc_proto_prices_proto_rawDescGZIP(), []int{1}
}

func (x *Pricing) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Pricing) GetTimeFrom() int64 {
	if x != nil {
		return x.TimeFrom
	}
	return 0
}

func (x *Pricing) GetTimeTo() int64 {
	if x != nil {
		return x.TimeTo
	}
	return 0
}

func (x *Pricing) GetData() []*Pricing_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Pricing_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time             int64   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	High             float32 `protobuf:"fixed32,2,opt,name=high,proto3" json:"high,omitempty"`
	Low              float32 `protobuf:"fixed32,3,opt,name=low,proto3" json:"low,omitempty"`
	Open             float32 `protobuf:"fixed32,4,opt,name=open,proto3" json:"open,omitempty"`
	Close            float32 `protobuf:"fixed32,5,opt,name=close,proto3" json:"close,omitempty"`
	ConversionType   string  `protobuf:"bytes,6,opt,name=conversionType,proto3" json:"conversionType,omitempty"`
	ConversionSymbol string  `protobuf:"bytes,7,opt,name=conversionSymbol,proto3" json:"conversionSymbol,omitempty"`
}

func (x *Pricing_Data) Reset() {
	*x = Pricing_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_proto_prices_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pricing_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pricing_Data) ProtoMessage() {}

func (x *Pricing_Data) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_prices_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pricing_Data.ProtoReflect.Descriptor instead.
func (*Pricing_Data) Descriptor() ([]byte, []int) {
	return file_grpc_proto_prices_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Pricing_Data) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Pricing_Data) GetHigh() float32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Pricing_Data) GetLow() float32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Pricing_Data) GetOpen() float32 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Pricing_Data) GetClose() float32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Pricing_Data) GetConversionType() string {
	if x != nil {
		return x.ConversionType
	}
	return ""
}

func (x *Pricing_Data) GetConversionSymbol() string {
	if x != nil {
		return x.ConversionSymbol
	}
	return ""
}

var File_grpc_proto_prices_proto protoreflect.FileDescriptor

var file_grpc_proto_prices_proto_rawDesc = []byte{
	0x0a, 0x17, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x43, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22,
	0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0xce, 0x02, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x50, 0x72,
	0x69, 0x63, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x69,
	0x63, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a,
	0xbe, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x69, 0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68,
	0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c,
	0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x32, 0x6f, 0x0a, 0x14, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e,
	0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x22,
	0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x50, 0x72, 0x69, 0x63, 0x69,
	0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e,
	0x67, 0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_prices_proto_rawDescOnce sync.Once
	file_grpc_proto_prices_proto_rawDescData = file_grpc_proto_prices_proto_rawDesc
)

func file_grpc_proto_prices_proto_rawDescGZIP() []byte {
	file_grpc_proto_prices_proto_rawDescOnce.Do(func() {
		file_grpc_proto_prices_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_prices_proto_rawDescData)
	})
	return file_grpc_proto_prices_proto_rawDescData
}

var file_grpc_proto_prices_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_proto_prices_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil), // 0: CryptoPricingService.EmptyRequest
	(*Pricing)(nil),      // 1: CryptoPricingService.Pricing
	(*Pricing_Data)(nil), // 2: CryptoPricingService.Pricing.Data
}
var file_grpc_proto_prices_proto_depIdxs = []int32{
	2, // 0: CryptoPricingService.Pricing.data:type_name -> CryptoPricingService.Pricing.Data
	0, // 1: CryptoPricingService.CryptoPricingService.GetHistoricalPrice:input_type -> CryptoPricingService.EmptyRequest
	1, // 2: CryptoPricingService.CryptoPricingService.GetHistoricalPrice:output_type -> CryptoPricingService.Pricing
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_prices_proto_init() }
func file_grpc_proto_prices_proto_init() {
	if File_grpc_proto_prices_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_proto_prices_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_prices_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pricing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_proto_prices_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pricing_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_prices_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_prices_proto_goTypes,
		DependencyIndexes: file_grpc_proto_prices_proto_depIdxs,
		MessageInfos:      file_grpc_proto_prices_proto_msgTypes,
	}.Build()
	File_grpc_proto_prices_proto = out.File
	file_grpc_proto_prices_proto_rawDesc = nil
	file_grpc_proto_prices_proto_goTypes = nil
	file_grpc_proto_prices_proto_depIdxs = nil
}
